### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yh406** [yh406/furima-30541#9]
＜自身のフリマアプリのURL＞
https://furima-30541.herokuapp.com/

＜Basic認証＞
ID:admin
パスワード:r8w65yea

＜出品者＞
メールアドレス：test@com
パスワード：1q2w3e

＜購入者＞
メールアドレス：gogo@test.com
パスワード：0p9o8i

＜購入用カード＞
番号：4242424242424242
期限：4月/23年
セキュリティコード：123

**Comment by tomoko-yokoyama** [comment]
原さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
